name: "Open Github Issue"
author: Ragu
description: "Opens a github issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
  assignees:
    description: "Issue Assignees"
outputs:
  issue:
    description: 'The issue object as as json string'
runs:
  using: 'node12'
  main: 'dist/index.js'